### ISSUE TITLE
Support for laravel scout 5

### ISSUE THREAD

**Issue by qqjt** [ErickTamayo/laravel-scout-elastic#107]
laravel scout has upgrade to v5.0+, does laravel scout elastic support v5 too?

**Comment by kronthto** [comment]
I just proposed https://github.com/ErickTamayo/laravel-scout-elastic/pull/106

**Comment by varunsngl** [comment]
Please provide, We also love this driver

**Comment by iraklisg** [comment]
@qqjt `laravel-scout-driver^4.0` supports elasticsearch v5 as you can see [here](https://github.com/ErickTamayo/laravel-scout-elastic/blob/fb5b843c0091972153cf36e009d53a631b2ec9da/composer.json#L8)
