### ISSUE TITLE
Error with install on elasticsearch 6

### ISSUE THREAD

**Issue by simonproud** [ErickTamayo/laravel-scout-elastic#109]
Problem 1
    - Can only install one of: elasticsearch/elasticsearch[5.0.x-dev, v6.0.1].
    - Can only install one of: elasticsearch/elasticsearch[v6.0.1, 5.0.x-dev].
    - Can only install one of: elasticsearch/elasticsearch[5.0.x-dev, v6.0.1].
    - tamayo/laravel-scout-elastic 4.0.0 requires elasticsearch/elasticsearch ^5.0 -> satisfiable by elasticsearch/elasticsearch[5.0.x-dev].
    - Installation request for tamayo/laravel-scout-elastic ^4.0 -> satisfiable by tamayo/laravel-scout-elastic[4.0.0].
    - Installation request for elasticsearch/elasticsearch == 6.0.1.0 -> satisfiable by elasticsearch/elasticsearch[v6.0.1].

**Comment by pablosebastianr** [comment]
Similar problem
Trying to install this on a clean laravel 5.6.* installation
These are the requires on my composer.json


```
{
	"require": {
		"php": "^7.1.3",
		"elasticsearch/elasticsearch": "^6.1",
		"fideloper/proxy": "^4.0",
		"laravel/framework": "5.6.*",
		"laravel/scout": "^7.1",
		"laravel/tinker": "^1.0"
	},
	"require-dev": {
		"filp/whoops": "^2.0",
		"fzaninotto/faker": "^1.4",
		"mockery/mockery": "^1.0",
		"nunomaduro/collision": "^2.0",
		"phpunit/phpunit": "^7.0"
	}
}
```
And this is the error I get:

  Problem 1
    - Can only install one of: elasticsearch/elasticsearch[5.0.x-dev, v6.1.0].
    - Can only install one of: elasticsearch/elasticsearch[v6.1.0, 5.0.x-dev].
    - Can only install one of: elasticsearch/elasticsearch[5.0.x-dev, v6.1.0].
    - tamayo/laravel-scout-elastic 4.0.0 requires elasticsearch/elasticsearch ^5.0 -> satisfiable by elasticsearch/elasticsearch[5.0.x-dev].
    - Installation request for tamayo/laravel-scout-elastic ^4.0 -> satisfiable by tamayo/laravel-scout-elastic[4.0.0].
    - Installation request for elasticsearch/elasticsearch ^6.1 -> satisfiable by elasticsearch/elasticsearch[v6.1.0].

**Comment by artsur** [comment]
Try to write in composer.json:
```
"require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.6.*",
        "laravel/tinker": "^1.0",
        "tamayo/laravel-scout-elastic": "*",
        . . .
    },
```
