### ISSUE TITLE
Elastic Cloud Authentication

### ISSUE THREAD

**Issue by louiscoetzee** [ErickTamayo/laravel-scout-elastic#114]
hi there, please help. how do I send a username and password? I've signed up for elasticsearch cloud. help will be appreciated.

**Comment by yakidahan** [comment]
Hi @louiscoetzee,

In the host configuration you pass the username and password

`ELASTICSEARCH_HOST=https://username:password@xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.eu-central-1.aws.cloud.es.io:9243`

**Comment by lalitvohra** [comment]
i have @ in the password, how do I solve that ?
