### ISSUE TITLE
Error: Content-Type header [] is not supported

### ISSUE THREAD

**Issue by alkhachatryan** [ErickTamayo/laravel-scout-elastic#116]
Hi. I have indexed one table into elasticsearch. When I do search with eloquent I get this error 

![image](https://user-images.githubusercontent.com/22774727/50339917-4bd0f580-0532-11e9-9934-64443bc8bd21.png)

When send CURL GET request I get empty array 
![image](https://user-images.githubusercontent.com/22774727/50339934-59867b00-0532-11e9-83a9-b941ae3fd935.png)

But I already imported model
php artisan scout:import "App\Model"

When I second time run import command I get the same error
{"error":"Content-Type header [] is not supported","status":406}

What is it? I cannot find a solution 3 days.

I use:
OS: Ubuntu16.04
PHP: 7.2
Laravel: 5.7
elasticsearch/elasticsearch: 5.0
tamayo/laravel-scout-elastic: ^4.0

Elasticserver is ran, I checked

**Comment by rodolfobarretoweb** [comment]
I have this problem too

**Comment by alkhachatryan** [comment]
@ErickTamayo any solution?

**Comment by alkhachatryan** [comment]
This issue opened for 100 days and there is no solution since

**Comment by alkhachatryan** [comment]
@ErickTamayo the issue opened more then a year ago, but there is no solution still

**Comment by ErickTamayo** [comment]
PRs are welcome
