### ISSUE TITLE
Bulk Indexing huge database

### ISSUE THREAD

**Issue by pvanhemmen** [ErickTamayo/laravel-scout-elastic#12]
Hey Erick,

I have a database with a fairly amount of entries (30,000+) for one of my models. I have set up queueing for indexing to reduce the initial load. Nonetheless when I try to bulk index the models with the elasticsearch driver the indexing process is nearly brought down to its knees.

I think one part of the problem could be how the `ElasticsearchEngine->update()` method prepares the data for indexing. In my case the method receives like ~12.000  models at once. While mapping is done in about 1-2 seconds, calling `->flatten(1)->toArray()` on the mapped data will take about 3+ minutes.

The other part is that 12,000 models at once is way too much for like every one of the ~300 jobs created for queueing IMO, but that again is clearly not happening on your side. Maybe you have an idea why the amount of models is that high with every job processed? In the end there are like 100 docs created with every job.

If needed, I can create a pull request with a modified handler to process the models in smaller chunks.

Thanx for bringing elasticsearch to the table anyway!

**Comment by ErickTamayo** [comment]
Hey @pvanhemmen, Yeah I feel a bit guilty I didn't test with that much data (just about 1000 docs). Of course you can feel free make any PR that can help with the performance.
