### ISSUE TITLE
Cannot install with Laravel 5.8

### ISSUE THREAD

**Issue by alexkorsukov** [ErickTamayo/laravel-scout-elastic#121]
Git this

composer require tamayo/laravel-scout-elastic
Using version ^5.0 for tamayo/laravel-scout-elastic
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: elasticsearch/elasticsearch[5.0.x-dev, v6.7.1].
    - Can only install one of: elasticsearch/elasticsearch[v6.7.1, 5.0.x-dev].
    - Can only install one of: elasticsearch/elasticsearch[5.0.x-dev, v6.7.1].
    - tamayo/laravel-scout-elastic 5.0.0 requires elasticsearch/elasticsearch ^5.0 -> satisfiable by elasticsearch/elasticsearch[5.0.x-dev].
    - Installation request for tamayo/laravel-scout-elastic ^5.0 -> satisfiable by tamayo/laravel-scout-elastic[5.0.0].
    - Installation request for elasticsearch/elasticsearch (locked at v6.7.1, required as ^6.7) -> satisfiable by elasticsearch/elasticsearch[v6.7.1].

Installation failed, reverting ./composer.json to its original content.

Is there a roadmap for Laravel 5.8 ?

Thanks

**Comment by ErickTamayo** [comment]
I will take a look ASAP

**Comment by ErickTamayo** [comment]
I think you're explicitly using  elasticsearch/elasticsearch v6.7.1 in your composer.json. Do you need it or can you remove it from there?

**Comment by netEmmanuel** [comment]
I have this same issue

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: elasticsearch/elasticsearch[7.0.x-dev, 5.0.x-dev].
    - Can only install one of: elasticsearch/elasticsearch[v7.0.0, 5.0.x-dev].
    - Can only install one of: elasticsearch/elasticsearch[v7.0.1, 5.0.x-dev].
    - tamayo/laravel-scout-elastic 5.0.0 requires elasticsearch/elasticsearch ^5.0 -> satisfiable by elasticsearch/elasticsearch[5.0.x-dev].
    - Installation request for tamayo/laravel-scout-elastic ^5.0 -> satisfiable by tamayo/laravel-scout-elastic[5.0.0].
    - Installation request for elasticsearch/elasticsearch ^7.0 -> satisfiable by elasticsearch/elasticsearch[7.0.x-dev, v7.0.0, v7.0.1].
```

composer.json
"require": {
    "php": "^7.1.3",
    "elasticsearch/elasticsearch": "^7.0",
    "fideloper/proxy": "^4.0",
    "laravel/framework": "5.6.*",
  }

**Comment by netEmmanuel** [comment]
I have this same issue

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: elasticsearch/elasticsearch[7.0.x-dev, 5.0.x-dev].
    - Can only install one of: elasticsearch/elasticsearch[v7.0.0, 5.0.x-dev].
    - Can only install one of: elasticsearch/elasticsearch[v7.0.1, 5.0.x-dev].
    - tamayo/laravel-scout-elastic 5.0.0 requires elasticsearch/elasticsearch ^5.0 -> satisfiable by elasticsearch/elasticsearch[5.0.x-dev].
    - Installation request for tamayo/laravel-scout-elastic ^5.0 -> satisfiable by tamayo/laravel-scout-elastic[5.0.0].
    - Installation request for elasticsearch/elasticsearch ^7.0 -> satisfiable by elasticsearch/elasticsearch[7.0.x-dev, v7.0.0, v7.0.1].
```

composer.json
```
"require": {
    "php": "^7.1.3",
    "elasticsearch/elasticsearch": "^7.0",
    "fideloper/proxy": "^4.0",
    "laravel/framework": "5.6.*",
  }

```

**Comment by netEmmanuel** [comment]
I have this same issue

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: elasticsearch/elasticsearch[7.0.x-dev, 5.0.x-dev].
    - Can only install one of: elasticsearch/elasticsearch[v7.0.0, 5.0.x-dev].
    - Can only install one of: elasticsearch/elasticsearch[v7.0.1, 5.0.x-dev].
    - tamayo/laravel-scout-elastic 5.0.0 requires elasticsearch/elasticsearch ^5.0 -> satisfiable by elasticsearch/elasticsearch[5.0.x-dev].
    - Installation request for tamayo/laravel-scout-elastic ^5.0 -> satisfiable by tamayo/laravel-scout-elastic[5.0.0].
    - Installation request for elasticsearch/elasticsearch ^7.0 -> satisfiable by elasticsearch/elasticsearch[7.0.x-dev, v7.0.0, v7.0.1].
```

composer.json

```
"require": {
    "php": "^7.1.3",
    "elasticsearch/elasticsearch": "^7.0",
    "fideloper/proxy": "^4.0",
    "laravel/framework": "5.6.*",
  }

```

**Comment by venkatavinash** [comment]
Any one solved this. Please reply.
