### ISSUE TITLE
Pagination error: Unsupported operand types

### ISSUE THREAD

**Issue by minkmk94** [ErickTamayo/laravel-scout-elastic#123]
Im using Model::search('something')->paginate() to get data but i got this error:
"Unsupported operand types" at ElasticsearchEngine.php line 118:
$result['nbPages'] = $result['hits']['total']/$perPage;
I try to dump $result and realize $result['hits']['total'] is array, and i found this link https://www.elastic.co/guide/en/elasticsearch/reference/master/search-request-track-total-hits.html. Elasticsearch return total is array include "value" and "relation". So how to fix this?. 
Im newbie and i need support. Sorry for bad English

**Comment by Julinar** [comment]
I have the same problem,
a temporarily solution is to dix the ElasticsearchEngine.php
$result['nbPages'] = $result['hits']['total']/$perPage; => $result['nbPages'] = $result['hits']['total']['value']/$perPage;

**Comment by minkmk94** [comment]
> I have the same problem,
> a temporarily solution is to dix the ElasticsearchEngine.php
> $result['nbPages'] = $result['hits']['total']/$perPage; => $result['nbPages'] = $result['hits']['total']['value']/$perPage;

i fixed this error like you but i still got error. So my temporarily solution is:
 $result['hits']['total'] =  $result['hits']['total']['value'] and it working.

**Comment by Julinar** [comment]
> > I have the same problem,
> > a temporarily solution is to dix the ElasticsearchEngine.php
> > $result['nbPages'] = $result['hits']['total']/$perPage; => $result['nbPages'] = $result['hits']['total']['value']/$perPage;
> 
> i fixed this error like you but i still got error. So my temporarily solution is:
> $result['hits']['total'] = $result['hits']['total']['value'] and it working.

But does the pagination is not broke like that ?

**Comment by minkmk94** [comment]
> > > I have the same problem,
> > > a temporarily solution is to dix the ElasticsearchEngine.php
> > > $result['nbPages'] = $result['hits']['total']/$perPage; => $result['nbPages'] = $result['hits']['total']['value']/$perPage;
> > 
> > 
> > i fixed this error like you but i still got error. So my temporarily solution is:
> > $result['hits']['total'] = $result['hits']['total']['value'] and it working.
> 
> But does the pagination is not broke like that ?

The pagination working fine, you can try that until official solution is out

**Comment by beaplat-61f** [comment]
> > I have the same problem,
> > a temporarily solution is to dix the ElasticsearchEngine.php
> > $result['nbPages'] = $result['hits']['total']/$perPage; => $result['nbPages'] = $result['hits']['total']['value']/$perPage;
> 
> i fixed this error like you but i still got error. So my temporarily solution is:
> $result['hits']['total'] = $result['hits']['total']['value'] and it working.

Thanks a lot, this solved my problem

**Comment by anton-reviakin** [comment]
Why issue is closed? Problem is keep...

**Comment by minkmk94** [comment]
> Why issue is closed? Problem is keep...

Problem is resolved, see this commit from author: https://github.com/morfeylatulipe/laravel-scout-elastic/commit/4e5eb7e7d5637c92dbefbfe63c15284384c81e69
