### ISSUE TITLE
Question regarding Order by highest _score?

### ISSUE THREAD

**Issue by Don404** [ErickTamayo/laravel-scout-elastic#125]
Hello, I have installed this package successfully and all is working fine. For 2 days I am wondering and trying to order my results by highest "_score" how can I do this? Thank you for the time in advance!!!

**Comment by Julinar** [comment]
You can do it simply with orderBy :

$model->search('myword')->orderBy('_score', 'desc');

**Comment by Don404** [comment]
> You can do it simply with orderBy :
> 
> $model->search('myword')->orderBy('_score', 'desc');

I tried this code. It is not taking any effect at all ordering the results. I set this:

`$searched = Model::search($q)->orderBy('_score', 'desc')->get();`

and there is no effect. If I `dd($searched = Model::search($q)->orderBy('_score', 'desc'))` I get the following result:

`Builder {#508 ▼
  +model: Model {#483 ▶}
  +query: "the test name"
  +callback: null
  +queryCallback: null
  +index: null
  +wheres: []
  +limit: null
  +orders: array:1 [▼
    0 => array:2 [▼
      "column" => "_score"
      "direction" => "desc"
    ]
  ]
}`

I have results that are named `Test name` but it always shows me the first result, which is `The first one` it is not ordering my results by relevance, but by ID I think. My goal is to sort them by relevance of the combination of several words in the title field.

**Comment by Julinar** [comment]
Can you ty change ElasticsearchEngine.php sort function by : 



> protected function sort($builder)
>    {
>        if (count($builder->orders) == 0) {
>            return null;
>        }
>        return collect($builder->orders)->map(function($order) {
>            return [$order['column'] => ['order' => $order['direction']]];
>        })->toArray()[0];
>    }
>

**Comment by Don404** [comment]
> Can you ty change ElasticsearchEngine.php sort function by :
> 
> > protected function sort($builder)
> > {
> > if (count($builder->orders) == 0) {
> > return null;
> > }
> > return collect($builder->orders)->map(function($order) {
> > return [$order['column'] => ['order' => $order['direction']]];
> > })->toArray()[0];
> > }

I just tried it and nothing changed. The results are the same. Ordered by ID ASC, and not by relevance. :(

**Comment by Julinar** [comment]
Maybe it's related to https://github.com/laravel/scout/issues/341
can you check there ?

**Comment by Julinar** [comment]
Ok it's the same kind of issue,
just change the map function by the one on this file :
https://gist.github.com/Julinar/d42d3a9831c416416eb9f7ab52d74702
and it must work :)

**Comment by Don404** [comment]
> Maybe it's related to [laravel/scout#341](https://github.com/laravel/scout/issues/341)
> can you check there ?

Thank you, I managed to fix they issue by changing the `public function map` in `ElasticsearchEngine.php`

The new function looks like this:

```
public function map(Builder $builder, $results, $model)
    {
        if ($results['hits']['total'] === 0) {
            return $model->newCollection();
        }

        $keys = collect($results['hits']['hits'])->pluck('_id')->values()->all();

        return $model->getScoutModelsByIds(
                $builder, $keys
            )->filter(function ($model) use ($keys) {
                return in_array($model->getScoutKey(), $keys);
            })->sortBy(function($model) use ($keys) {
                return array_search($model->getScoutKey(), $keys);
            });
    }
```

**Comment by Julinar** [comment]
please keep it open so they can fix it later here

**Comment by Don404** [comment]
Okay. Thank you again for the help!
