### ISSUE TITLE
Laravel 5.8 Unsupported operand types 

### ISSUE THREAD

**Issue by haoqianlei** [ErickTamayo/laravel-scout-elastic#130]
Edition
  Elasticsearch : "7.3.0"
  tamayo/laravel-scout-elastic ："5.0"
  Laravel : "5.8"
![image](https://user-images.githubusercontent.com/22309178/63254222-f0642c80-c2a5-11e9-8da5-05048370a3ce.png)
The problem is line 120 of the src/ElasticsearchEngine.php file. This print is an array type, not a number. I solved the problem in the following way
![image](https://user-images.githubusercontent.com/22309178/63253813-1fc66980-c2a5-11e9-97f9-495d9f8d22f9.png)

**Comment by lvtu0316** [comment]
我也遇到同样的问题，使用的是 Elasticsearch : "7.3.0"，换成Elasticsearch 5.6就没这个问题了，版本不兼容吧！
