### ISSUE TITLE
map do not sort by elastic result

### ISSUE THREAD

**Issue by Alamo19** [ErickTamayo/laravel-scout-elastic#137]
public function map(Builder $builder, $results, $model)
    {
        if ($results['hits']['total'] === 0) {
            return $model->newCollection();
        }
        $keys = collect($results['hits']['hits'])->pluck('_id')->values()->all();
        return $model->getScoutModelsByIds(
                $builder, $keys
            )->filter(function ($model) use ($keys) {
                return in_array($model->getScoutKey(), $keys);
            });
    }

**Comment by CasperLaiTW** [comment]
should be fix soon #142 
PR is ready.
