### ISSUE TITLE
laravel 7 is not compatible

### ISSUE THREAD

**Issue by renlikang** [ErickTamayo/laravel-scout-elastic#138]
the package is not compatible laravel7

**Comment by william-tokoplas** [comment]
> the package is not compatible laravel7

same with me when i tried to composer require tamayo/laravel-scout-elastic it gave me an error : 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for tamayo/laravel-scout-elastic ^5.0 -> satisfiable by tamayo/laravel-scout-elastic[5.0.0].
    - Conclusion: remove elasticsearch/elasticsearch v7.8.0
    - Conclusion: don't install elasticsearch/elasticsearch v7.8.0
    - tamayo/laravel-scout-elastic 5.0.0 requires elasticsearch/elasticsearch ^5.0 -> satisfiable by elasticsearch/elasticsearch[5.0.x-dev, 5.x-dev].
    - Can only install one of: elasticsearch/elasticsearch[5.0.x-dev, v7.8.0].
    - Can only install one of: elasticsearch/elasticsearch[5.x-dev, v7.8.0].
    - Installation request for elasticsearch/elasticsearch (locked at v7.8.0, required as ^7.8) -> satisfiable by elasticsearch/elasticsearch[v7.8.0].


Installation failed, reverting ./composer.json to its original content.

Anyone having the same issue with me or does anyone have the solution? please help me

**Comment by artsur** [comment]
Working with `"tamayo/laravel-scout-elastic": "*"` in composer.json

**Comment by ErickTamayo** [comment]
Are you guys switching to Laravel 8 or planning to stay on 7? I just released a new version for Laravel 8 but I'm wondering if I need to support the 7 depending on what people need.
