### ISSUE TITLE
lumen8 use paginate error,

### ISSUE THREAD

**Issue by ghost** [ErickTamayo/laravel-scout-elastic#149]
model::search($name)->simplePaginate($pageSize, '', $page);

report:
vendor/tamayo/laravel-scout-elastic/src/Engines/ElasticsearchEngine.php 114 "Unsupported operand types"

**Comment by Mnikoei** [comment]
I have same issue in laravel 8.

**Comment by SergeyOsipoff** [comment]
The problem is in this file: src / Engines / ElasticsearchEngine.php

Wherever there is `['hits']['total']` (3 places in the file) should be replaced with `['hits']['total']['value']`
