### ISSUE TITLE
Warning about type deprecation

### ISSUE THREAD

**Issue by mlambley** [ErickTamayo/laravel-scout-elastic#152]
I did find some chatter about this in your issue log but I can see that it hasn't been resolved so I'm posting it here.
```
<warning>PHP Deprecated:  Specifying types in urls has been deprecated in vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/Search.php on line 36</warning>
```

Code which causes this:
https://github.com/ErickTamayo/laravel-scout-elastic/blob/004c8fc0088bce96fde90bedca9c43346ce0bd3f/src/Engines/ElasticsearchEngine.php#L126-L130

I have noticed that scout's `searchableAs` by default includes the table name [(link)](https://github.com/laravel/scout/blob/0a8c73e715b80bfc7ab78374d9d67d3f94174f7a/src/Searchable.php#L242-L245)
```php
    public function searchableAs()
    {
        return config('scout.prefix').$this->getTable();
    }
```

So I would think that the only breaking change would be to require devs to specify their own searchableAs for models which don't map to a database table? Because otherwise the index would be unique anyway? Unless I'm not understanding the issue here.

**Comment by mlambley** [comment]
+1?

**Comment by mlambley** [comment]
Happy July to you too, stalebot.

**Comment by mlambley** [comment]
It's September already? Greetings once again my good friend stalebot.

**Comment by ascott-main** [comment]
Good morning!! Hi @mlambley I just see this and I am having the same issue, it looks like the import command with scout work perfectly but when I try to search for something have this issue 
```
<warning>PHP Deprecated:  Specifying types in URLs has been deprecated in /var/www/web/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/Search.php on line 36</warning>
Elasticsearch\Common\Exceptions\BadRequest400Exception with message '{"error":"no handler found for uri [//ascott_mdm_seasons/App%5CSeason/_search] and method [POST]"}'
```

Have you been able to fix this issue? Could you tell me how?

Thanks in advance.

**Comment by mlambley** [comment]
@ascott-main The fix is to remove `'type' => get_class($builder->model),` as described in my OP. I tried to get the repo author's attention over the course of several months. I recommend creating yourself a fork and removing that line of code.

**Comment by ascott-main** [comment]
@mlambley Thank you very much, I will try with that!!!
