### ISSUE TITLE
Pagination doesn't seem to work

### ISSUE THREAD

**Issue by aidabeorn** [ErickTamayo/laravel-scout-elastic#16]
I've indexed some 700k records and checked in elasticHQ what the query `*tux*`, that returns 114 records, same happens if I paginate a number higher than the expected numbers. but when I do

```
$players = User::search('tux')->paginate(24);
```

I get 24 results and an empty paginator.

**Comment by aidabeorn** [comment]
Might add that I'm currently on dev-master version of the engine.

**Comment by ErickTamayo** [comment]
Hello @thorerik, I will check on this later in the day when I have time. Not to boycott myself but if you need this working ASAP, Laravel Scout has its own elastic engine now that was recently merged, you can check that out.

**Comment by aidabeorn** [comment]
Thanks, that must have passed right under my radar while I've been working on our own stuff, thanks for giving me a headsup on a 1st party solution :)

**Comment by ErickTamayo** [comment]
NP 😄  I made the driver because there wasn't an elastic integration at that time, so this package has become a bit obsolete.

**Comment by aidabeorn** [comment]
maybe worth updating packagist to indicate that as well since most resources (laracast and the docs) kinda indicate that Algolia is the only driver around.

**Comment by aidabeorn** [comment]
To add to this in case someone else wanders by this issue, issue is caused by scout itself:
https://github.com/laravel/scout/pull/52

**Comment by ErickTamayo** [comment]
@thorerik I see a fix has been merged in the Scout repo, is this solved?

**Comment by aidabeorn** [comment]
Yes, I'm just waiting for them to tag it and maybe extend it to make scout able to do a lengthAwarePaginator instead.

**Comment by harlekoy** [comment]
Having the same problem here. Thanks @thorek for adding the `getTotalCount` but who will update the builder paginate method?

This solves my problem after adding these lines of code in laravel scout `src/Builder.php`.

``` php
        $paginator = (new LengthAwarePaginator($results, $engine->getTotalCount($rawResults), $perPage, $page, [
            'path' => Paginator::resolveCurrentPath(),
            'pageName' => $pageName,
        ]));
```

**Comment by aidabeorn** [comment]
@harlekoy: if you could make a PR to laravel/scout that'd be great, I'd rather not make any changes to upstream packages(maintenance hell)
