### ISSUE TITLE
Make it work with ES 7

### ISSUE THREAD

**Issue by jakobonline** [ErickTamayo/laravel-scout-elastic#160]
Hi there! Since ES 7 `$results['hits']['total']` isn't a number any more ([docu](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#hits-total-now-object-search-response)). 

So my engine keeps breaking. But after changing
~~~
public function getTotalCount($results)
    {
        return $results['hits']['total'];
    }
~~~
to
~~~
public function getTotalCount($results)
    {
        if(is_numeric($results['hits']['total'])){
            return $results['hits']['total']; 
        } else {
            return $results['hits']['total']['value'];
        }
    }
~~~
and use this function everywehre in the ElasticsearchEngine class, everythings returns to a running scout package.

Should I open a pull request?

**Comment by ErickTamayo** [comment]
A PR is very welcome! Thanks!

**Comment by Dani2kn** [comment]
Can we have this fix? 

Also: 

TypeError
Unsupported operand types: array / int

Tamayo\LaravelScoutElastic\Engines\ElasticsearchEngine::paginate
vendor/tamayo/laravel-scout-elastic/src/Engines/ElasticsearchEngine.php:114

`$result['nbPages'] = $result['hits']['total'] / $perPage;`

`$result['nbPages'] = $this->getTotalCount($result) / $perPage;`
