### ISSUE TITLE
ElasticClient namespace incompatible

### ISSUE THREAD

**Issue by czjge** [ErickTamayo/laravel-scout-elastic#164]
laravel V9
Elasticsearch PHP client V8.1.0
laravel-scout-elastic V8.1.0

Once I start server, it raises a error: Please install the Elasticsearch PHP client: elasticsearch/elasticsearch.

Then I changed "use Elasticsearch\ClientBuilder;" to "use Elastic\Elasticsearch\ClientBuilder;" in LaravelScoutElasticProvider, error went out.

**Comment by czjge** [comment]
Also, in ElasticsearchEngine the same thing should be done.

**Comment by amitleuva1987** [comment]
> laravel V9 Elasticsearch PHP client V8.1.0 laravel-scout-elastic V8.1.0
> 
> Once I start server, it raises a error: Please install the Elasticsearch PHP client: elasticsearch/elasticsearch.
> 
> Then I changed "use Elasticsearch\ClientBuilder;" to "use Elastic\Elasticsearch\ClientBuilder;" in LaravelScoutElasticProvider, error went out.

It worked for me

**Comment by amitleuva1987** [comment]
@czjge , did you get any error after making these fixes? I am getting below error after those 2 fixes in laravel 9.  I am getting this error while importing models into scout search (php artisan scout:import 'app\models\user')

Class "ScoutEngines\Elasticsearch\ElasticsearchProvider" not found

**Comment by FuviTeam** [comment]
> laravel V9 Elasticsearch PHP client V8.1.0 laravel-scout-elastic V8.1.0
> 
> Once I start server, it raises a error: Please install the Elasticsearch PHP client: elasticsearch/elasticsearch.
> 
> Then I changed "use Elasticsearch\ClientBuilder;" to "use Elastic\Elasticsearch\ClientBuilder;" in LaravelScoutElasticProvider, error went out.

Got the exact same trouble. Worked for me also

**Comment by FuviTeam** [comment]
> @czjge , did you get any error after making these fixes? I am getting below error after those 2 fixes in laravel 9. I am getting this error while importing models into scout search (php artisan scout:import 'app\models\user')
> 
> Class "ScoutEngines\Elasticsearch\ElasticsearchProvider" not found

same error too in your config/app.php replace by 
Tamayo\LaravelScoutElastic\LaravelScoutElasticProvider::class,
