### ISSUE TITLE
'_index' => $model->searchableAs(), '_type' => get_class($model),

### ISSUE THREAD

**Issue by wangchunabin** [ErickTamayo/laravel-scout-elastic#177]
High version elasticsearch‘s '_type' was abandoned；but this code uses model class name
![1661154927039](https://user-images.githubusercontent.com/20350991/185869415-e55062bf-83a0-4e7d-9647-99491efbba7b.jpg)
![1661155056155](https://user-images.githubusercontent.com/20350991/185869682-0088a6ee-f9b2-410a-a974-b4e080d3b24d.jpg)
；

**Comment by deadmerc** [comment]
Thanks for info, help a lot for resolve sync problem
