### ISSUE TITLE
not working with laravel mongodb

### ISSUE THREAD

**Issue by harryy2510** [ErickTamayo/laravel-scout-elastic#21]
I am using Jenssegers laravel mongodb package

https://github.com/jenssegers/laravel-mongodb/

On importing data through model, no mappings are created.
and search also doesnt gives any result
please help

User Model

`

```
protected $fillable = [
    'name', 'email', 'password',
];
protected $hidden = [
    'password', 'remember_token',
];
protected $dates = [
    'updated_at',
    'created_at'
];
```

`

scout.php

`

```
'driver' => env('SCOUT_DRIVER', 'elasticsearch'),

'prefix' => env('SCOUT_PREFIX', ''),

'queue' => false,

'elasticsearch' => [
    'index' => env('ELASTICSEARCH_INDEX', 'laravel'),
    'hosts' => [
        env('ELASTICSEARCH_HOST', 'http://192.168.10.10'),
    ],
],
```

`

**Comment by lucasmrg** [comment]
was it fixed? I'm having the same problem in Laravel v5.4.19, jenssegers/mongodb v3.2.2 and laravel-scout-elastic 3.0.2
