### ISSUE TITLE
Geospatial support

### ISSUE THREAD

**Issue by sandervanhooft** [ErickTamayo/laravel-scout-elastic#24]
@ErickTamayo How would you suggest doing geospatial search?

See also [this discussion at the Laravel Scout repo](https://github.com/laravel/scout/issues/12) by the way.

**Comment by ErickTamayo** [comment]
@sandervanhooft as the linked discussion we might need to extend at some point the Scout Query Builder class, I am planning to do so but not right now.

Probably in the next month will have some free time to extend the most common ES features.

**Comment by xcaptain** [comment]
Would be happy to see this feature implemented.

**Comment by xcaptain** [comment]
I wrote simple example to do geo query.

```
Model::search('some text', function ($engine, $query, $options) {
    $options['body']['query']['bool']['filter']['geo_distance'] = [
        'distance' => '1000km',
        'location' => ['lat' => 36, 'lon' => 111],
    ];
    return $engine->search($options);
})->get()->toArray();
```

it works for me, ping @ErickTamayo 
@sandervanhooft As you said, I created a mapping that has geo_location and then use `scout:import` to import data into ES.

```
curl -XPUT 'http://localhost:9200/some_index/_mapping/some_type' -d '
{
  "properties": {
    "location": {
      "type": "geo_point"
    }
  }
}
'
```

**Comment by zanematthew** [comment]
To add for others, you can easily add sorting as well. Just to add for any others that stumble across this. Its fairly easy to set this up based on the ES docs. 

```
Model::search('some text', function ($engine, $query, $options) {
    $options['body']['query']['bool']['filter']['geo_distance'] = [
        'distance' => '1000km',
        'location' => ['lat' => 36, 'lon' => 111],
    ];
    $options['body']['sort']['_geo_distance'] = [
            'latlon'        => '39.290385,-76.612189', // This is your field that contains the lat/long
            'order'         => 'desc',
            'unit'          => 'km',
            'mode'          => 'min',
            'distance_type' => 'arc',
    ];
    return $engine->search($options);
})->get()->toArray();
```

@xcaptain what you have is an ideal solution. Do you know if there are any issues with search and _not_ passing in a string, say if you want to _only_ search based on geolocation. I've tried `Foo::search('', function(...`, and results do _appear_ to display correctly, I'm just wondering if using `''` would cause issues down the road.
