### ISSUE TITLE
Error on queue importing (Abstract method)

### ISSUE THREAD

**Issue by cryptoBOOOOM** [ErickTamayo/laravel-scout-elastic#26]
Hey when i run my queue worker for importing i get the following error:

[Symfony\Component\Debug\Exception\FatalErrorException]
  Class ScoutEngines\Elasticsearch\ElasticsearchEngine contains 1 abstract me
  thod and must therefore be declared abstract or implement the remaining met
  hods (Laravel\Scout\Engines\Engine::getTotalCount)

**Comment by Melcus** [comment]
I created getTotalCount in vendor\tamayo\laravel-scout-elastic\src\ElasticsearchEngine.php

```

    public function getTotalCount($results)
    {
        return $results['hits']['total'];
    }
```

This might be wrong, but it gets rid of the error

**Comment by ErickTamayo** [comment]
@Melcus I've been a bit busy lately, can you fork and make a PR for this?

**Comment by Melcus** [comment]
You already merged https://github.com/ErickTamayo/laravel-scout-elastic/pull/25 , I don't know why it was missing

**Comment by ErickTamayo** [comment]
Alright. Thanks!

**Comment by Melcus** [comment]
I just reinstalled the package. It's still not including `getTotalCount` . This is odd. 
Do you plan on extending the package for more advanced queries?

**Comment by ErickTamayo** [comment]
What version do you have of this package?

**Comment by Melcus** [comment]
^1.0
