### ISSUE TITLE
Sort Support

### ISSUE THREAD

**Issue by deftstar** [ErickTamayo/laravel-scout-elastic#27]
why is there no support for sorting!. Elasticsearch does have sorting available. am i missing something here?

**Comment by ErickTamayo** [comment]
Hi @muhamin, right now Scout is a very simple package for full text search, afaik it doesn't have sorting, I just made the Elasticsearch driver.

I'm planning to extend scout query builder to support more Elasticsearch features in the near future. I will update the repo accordingly

**Comment by LuizPenha** [comment]
Hi,  @ErickTamayo! Do you have an update for this feature?
