### ISSUE TITLE
do it supports elasticsearch/elasticsearch ^5.0

### ISSUE THREAD

**Issue by aeroplane** [ErickTamayo/laravel-scout-elastic#29]
composer require elasticsearch/elasticsearch
the version is ^5.0

but your 'composer.json' is ^2.0

**Comment by huglester** [comment]
as I believe they are very different

there should probably two separete versions, like v1 for 2.x.x version
and v2 for v5.x.x

**Comment by ErickTamayo** [comment]
v2.0 supports ElasticSearch 5.x.x https://github.com/ErickTamayo/laravel-scout-elastic/commit/6125eaa2407ed41ad54769210aa71c55bb1a7a7c
