### ISSUE TITLE
require scout ^1

### ISSUE THREAD

**Issue by divdax** [ErickTamayo/laravel-scout-elastic#30]
laravel/scout currently is at v2. composer requires v1. any update? :smile: 
```
"require": {
    "laravel/scout": "^1.0",
},
```

**Comment by ErickTamayo** [comment]
Hey @divdax, I will take a look of the changes and bump the version in a couple of hours. If you need it asap you can make a PR and I will merge it right away

**Comment by aaposthumus** [comment]
Please bump it. :-) I tried to use this on the current version of Laravel with Scout v2 and now it doesn't install.

**Comment by huglester** [comment]
Hello,
maybe there are updates on this?

**Comment by gokhanyildiz** [comment]
Hi, I'm waiting for update :)

**Comment by ErickTamayo** [comment]
Hello guys, I'm sorry I've been slow on answering, I'm currently dealing with a personal matter, If you can bump it, I will be more than thankful to merge it.

**Comment by sergiocastrovale** [comment]
Waiting for an update as well :-)

**Comment by gokhanyildiz** [comment]
this package solved my problem. https://github.com/camry/scout

**Comment by subdesign** [comment]
@gokhanyildiz how did you install this fork? everything is namespaced with Laravel\Scout and not Camry\Scout..

**Comment by ErickTamayo** [comment]
Hello, I will be updating this week.

**Comment by gokhanyildiz** [comment]
@subdesign use this command: composer require camry/scout

**Comment by leu2tm** [comment]
@ErickTamayo any progress? :)

**Comment by dannysood** [comment]
@ErickTamayo Definitely looking forward for the update :)

**Comment by ErickTamayo** [comment]
https://github.com/ErickTamayo/laravel-scout-elastic/commit/6125eaa2407ed41ad54769210aa71c55bb1a7a7c bumps to v2.x.x of Scout and v5 of elasticsearch
