### ISSUE TITLE
Importing partially

### ISSUE THREAD

**Issue by thiagolcks** [ErickTamayo/laravel-scout-elastic#32]
Hi,

I have a table with more than 100k entries and running `scout:import MyModel` it's importing only 2210 entries. I'm testing it via `http://localhost:9200/laravel/my_index/_count`.

Any idea?

I have some smaller tables that it is working fine.

**Comment by ErickTamayo** [comment]
That's weird, can you check if you're running out of RAM?

**Comment by gibex** [comment]
I have the same issue
table records - 4700
imported - 270

Thanks

**Comment by thomasjsn** [comment]
I am successfully importing 18k records. Maybe there is some inconsistency with the data vs. the mapping for record 271, causing the importer to crash? Anything in the ElasticSearch log?

**Comment by gibex** [comment]
Thank you @thomasjsn ,

It's crashing on some Date fields: Cannot parse "0000-00-00": Value 0 for monthOfYear must be in the range [1,12]

**Comment by thomasjsn** [comment]
@ErickTamayo Pretty sure you can close this one.

**Comment by ErickTamayo** [comment]
@thomasjsn thanks
