### ISSUE TITLE
laravel/scout 3.0^ support

### ISSUE THREAD

**Issue by leu2tm** [ErickTamayo/laravel-scout-elastic#34]
When pulling down laravel scout through composer I'll get 3.0 and will causes dependency issues.

Will this be supported? :)

**Comment by ErickTamayo** [comment]
https://github.com/ErickTamayo/laravel-scout-elastic/commit/4199c44e16e17aab6c893b2ad2f68cbe616b79b3 Done :) Forgot to set v3.0 yesterday.

**Comment by leu2tm** [comment]
Cool thanks!
