### ISSUE TITLE
Return empty collection if models are not found.

### ISSUE THREAD

**Issue by sasin91** [ErickTamayo/laravel-scout-elastic#36]
I'm not sure if this is a problem that's working as intended.. 

However, when searching and the map method on ElasticSearchEngine is called, it only checks the results from elasticsearch..

What if the model was manually deleted from the database?
That would make it unable to find the $hit matching the id and generate a error 500 :)

**Comment by ErickTamayo** [comment]
If you delete manually your model from the DB you should get rid of the the document in Elasticsearch as well otherwise you will have an inconsistency. I don't know what's the behavior with the Algolia driver in the official package, have to check. 

Also I don't know if "hidding" this exception is healthy.

**Comment by sasin91** [comment]
In Algolia, it checks if the key isset before returning, avoiding Undefined offset errors, which is the actual error here .. :)

to mimic that behaviour, 
map method @ElasticsearchEngine could return a collection like this:
` 
return Collection::make($results['hits']['hits'])->map(function ($hit) use ($model, $models) {
                return isset($models[$hit['_id']])
                        ? $models[$hit['_id']]
                        : null;
        })->filter()->values();
`

**Comment by loranger** [comment]
This behaviour would also apply for soft deleted models which are actually imported, but cannot be retrieved and throws *Undefined Offset* exception 🤔

**Comment by ErickTamayo** [comment]
Yes it should not crash on soft deletes. I will have a look at it soon.
