### ISSUE TITLE
Query String Query Wildcard?

### ISSUE THREAD

**Issue by bearzk** [ErickTamayo/laravel-scout-elastic#41]
When using this package fresh, I cannot get search results, but after changing this line

https://github.com/ErickTamayo/laravel-scout-elastic/blob/3.0.1/src/ElasticsearchEngine.php#L134

to following:

```php
'must' => [['query_string' => [ 'query' => "\*{$builder->query}\*"]]]
```

it works. 

I've read on [elasticsearch official doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) that the `*` in query string query should be escaped, am I right here?

I'm new to both Scout and this package, so maybe it's just me using it wrongly.
But If this is the right way to fix, I'd love to offer a PR as well.

**Comment by thomasjsn** [comment]
There is something else wrong. The asterisks are wildcards, they must be escaped if you **don't** want them to be operators. As it says in the docs:

> If you need to use any of the characters which function as operators in your query itself (and not as operators), then you should escape them with a leading backslash.

So `*query*` is perfectly acceptable, and it means, `zero or more characters`query`zero or more characters`.

A leading wildcard is inefficient, but allowed.
