### ISSUE TITLE
Odd issue with import

### ISSUE THREAD

**Issue by gibex** [ErickTamayo/laravel-scout-elastic#43]
I'm using scout:import to push my data into local ES (OSX). All good.

When I try to use import on ubuntu 16.04 (forge) wi ES 5.2.2 nothing happens.
It says the import was successful, no log errors, nothing, but data isn't there. 

I can send data using curl, only the import doesn't work.

Thank you for any help you could provide

**Comment by ErickTamayo** [comment]
Can you check if saving a new model on the DB is storing it also in Elasticsearch? This may be a ENV var misconfiguration.

**Comment by gibex** [comment]
You were right, the issue came from this setting : QUEUE=redis. 
With QUEUE=sync all is fine (update/import)

Queue=redis:
health status index    uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   scout    SMVvMQuXTTG4FpYTfPuncQ   5   1          0            0       650b           650b
yellow open   tutorial yDiwkrXwRAuH4jz6n8V6UA   5   1          1            0        4kb            4kb

Queue=sync:
health status index    uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   scout    SMVvMQuXTTG4FpYTfPuncQ   5   1       4709            0      2.8mb          2.8mb
yellow open   tutorial yDiwkrXwRAuH4jz6n8V6UA   5   1          1            0        4kb            4kb


Thank you Erick

**Comment by gibex** [comment]
@ErickTamayo Shouldn't work with queues? The queue is true by default in config/scout.php

**Comment by ErickTamayo** [comment]
@gibex yes it should, this driver doesn't interact with queues directly, is Scout itself. If you need to use queues for Scout, you may check if the queue workers are running.
