### ISSUE TITLE
"Fuzzy" requests

### ISSUE THREAD

**Issue by igarbera** [ErickTamayo/laravel-scout-elastic#44]
Hello! Could you help me, how can I use laravel-scout-elastic with fuzzy search, like this: 

# curl -XGET 'localhost:9200/_search?pretty' -H 'Content-Type: application/json' -d'
{
    "query": {
       "fuzzy" : { "name" : "нjальник" }
    }
}
'

**Comment by ErickTamayo** [comment]
Right now is not possible. Tho theres a PR that will enable that kind of
custom queries you can check in the meantime a fork of it here:
https://github.com/thomasjsn/laravel-scout-elastic
