### ISSUE TITLE
How can I set the created_at field type as date?

### ISSUE THREAD

**Issue by gitstashgithub** [ErickTamayo/laravel-scout-elastic#47]
I have a searchable model which has the standard `created_at` and `updated_at` fields. When I run 
`curl -XGET 'localhost:9200/laravel/_mapping/my_table?pretty'`, these two fields are both "text" type.
```
 "created_at" : {
                "type" : "text",
                "fields" : {
                  "keyword" : {
                    "type" : "keyword",
                    "ignore_above" : 256
                  }
                }
              }
```
Is there a way to save them as date type? Thanks.

**Comment by ErickTamayo** [comment]
You may need to manually create the document mapping for your models (at least for now) which probably includes redoing the index from the scratch, mapping then reindexing all your data again.

check https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html.
