### ISSUE TITLE
I am facing a problem  createDriver() .

### ISSUE THREAD

**Issue by mostafa6765** [ErickTamayo/laravel-scout-elastic#49]
ErrorException in Manager.php line 77:
Missing argument 1 for Illuminate\Support\Manager::createDriver(), called in C:\Users\MD.MOSTAFA KAMAL\ela-search\vendor\laravel\framework\src\Illuminate\Support\Manager.php on line 87 and defined

**Comment by ErickTamayo** [comment]
What version of the driver/scout/laravel are you using?

**Comment by mostafa6765** [comment]
laravel 5.4 , @ErickTamayo help me dear I am following this [medium source all code](https://medium.com/@samogorm/basic-search-functionality-with-elasticsearch-laravel-scout-6ac182c99cbf)

**Comment by dermatzeimnetz** [comment]
Got the same Problem as well, using Lara 5.4.19, ElasticSearch 5.2.0, your Driver 3.0.2 and Scout 3.0.3

Nevermind i found it, i had to  "php artisan config:cache", otherwise the host is not set. Please update your Documentation. Thanks for the driver :)
