### ISSUE TITLE
 No alive nodes found in your cluster error

### ISSUE THREAD

**Issue by 9IPHP** [ErickTamayo/laravel-scout-elastic#5]
When I run `php artisan scout:import App\\Post`, I got the error:

```
local.ERROR: Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found in your cluster
```

And I found a mistake in `ElasticsearchProvider`:

``` php
return new ElasticsearchEngine(ElasticBuilder::create()
                ->setHosts(config('scout.elastic.hosts'))
                ->build(),
                config('scout.elasticsearch.index')
            );
```

there are `elastic.hosts` and `elasticsearch.index` in this code. But add

```
    'elasticsearch' => [
        'index' => env('ELASTICSEARCH_INDEX', 'laravel'),
        'hosts' => [
            env('ELASTICSEARCH_HOST', 'http://localhost/'),
        ],
    ],
```

in the `scout.php` file.

I changed `scout.elastic.hosts` to `scout.elasticsearch.hosts` but still get that error.

**Comment by ErickTamayo** [comment]
Yeah this is a mistake, I will correct that in a couple of hours.

Changing the key to `scout.elasticsearch.hosts` Should fix your issue, do you have your elastic installation running on the same server as your Laravel installation?

**Comment by 9IPHP** [comment]
@ErickTamayo Yeah, I just forgot to setup elastic in my homestead. Thanks. I will close this.

**Comment by ErickTamayo** [comment]
Don't close it as the key needs to be changed anyway in the service provider

**Comment by 9IPHP** [comment]
Another question. I created 300 posts using faker, for a given word, It has total 124 records. But if I use paginate to set 10 records every page, and use `{{ $posts->appends(['s' => $s])->links() }}` to show pages. It only show disabled < and  > , no 1 / 2 / 3 in the pagination. And if I change page to 2, there also have records. Why this?

**Comment by ErickTamayo** [comment]
That's weird, I will have to check that, that should be working out of the box because the pagination itself  is untouched on the driver
