### ISSUE TITLE
how search with relations?

### ISSUE THREAD

**Issue by paulocastellano** [ErickTamayo/laravel-scout-elastic#52]
Hi,

How setup this search?

Ex: calendar app.

Find events with author data.

Thanks

**Comment by grasmanek94** [comment]
In `toSearchableArray` you can include all your needed relations like

    public function toSearchableArray()
    {
        $arr = array_only($this->toArray(), ['id', 'name', 'title']);
        $arr['author'] = $this->author->toSearchableArray();
        return $arr;
    }

When your `author` data changes you'll need to reindex all relations too, else your data will get out of sync. You can then search by fields from your `author` model like `author.id` etc.
