### ISSUE TITLE
toSearchableArray() does not work

### ISSUE THREAD

**Issue by joelarmad** [ErickTamayo/laravel-scout-elastic#57]
I define the method toSearchableArray() in my model, redefining the array that should be indexed but somehow I always have the default array indexed ($this-toArray()). Can anybody give a clue about this issue? Here is my code:

```
public function toSearchableArray()
    {
        if($this->folleto->catalogo->Vigente() && !($this->esExcursion()) && $this->PrecioMinimo()){
            
            $my_array = array();
            $my_array['id'] = $this->id;
            $my_array['code'] = $this->folleto->codcomis.'-'.$this->coditine;
            $my_array['price'] = $this->PrecioMinimo();
            $my_array['days'] = sprintf("%02d", $this->numedias);           
            return $my_array;           
        }
        else
            return [];
    }
```

**Comment by joelarmad** [comment]
Sorry, I figure out that my method is working fine I just was incapable of seeing what was actually indexed...

**Comment by grasmanek94** [comment]
Hello, if this issue is resolved, could you please close it? :)

**Comment by joelarmad** [comment]
He @grasmanek94 me method works from the beginning, but tell me what your problem is and I will try to help you.

**Comment by grasmanek94** [comment]
I have no issues over here, just mentioning that if this issue is no longer applicable that you can close it so the package maintainer can quickly / in a glance know which issues are still active.

**Comment by joelarmad** [comment]
I think it should be closed but I can´t

**Comment by grasmanek94** [comment]
There should be a "Close Issue" button left to the "Comment" button: http://i.imgur.com/X5O8VaA.png

**Comment by joelarmad** [comment]
I did it but this button was not there one month ago.

**Comment by robbietorinit** [comment]
@joelarmad : Could you please tell me what was the solution, As I am stucked to the same point!!
