### ISSUE TITLE
Add Elasticsearch "fuzzy" search feature

### ISSUE THREAD

**Issue by zvermafia** [ErickTamayo/laravel-scout-elastic#59]
Add this feature, please! I red about this here: [Learning Elasticsearch with Laravel](https://michaelstivala.com/learning-elasticsearch-with-laravel/)

**Comment by tumainimosha** [comment]
plus one on this feature... would be a good one to have

**Comment by kronthto** [comment]
It should be possible to do this already by modifying the query array using the callback parameter passed to `search`.

**Comment by zvermafia** [comment]
@kronthto could you show us an example?

**Comment by kronthto** [comment]
Somewhat like this (not tested):
``` php
/** @var \Laravel\Scout\Builder $builder */
$builder = MyModel::search(
    'searchstring',
    function (\Elasticsearch\Client $client, $query, $params) {
        $params['body']['query'] = [
            'multi_match' => [
                'query' => $query,
                'fuzziness' => 'AUTO',
                'fields' => ['title^3', 'content'],
            ],
        ];

        return $client->search($params);
    }
);
```
Be careful not to override other filters set via `Builder::where` in the callback.

I agree it would be nice if the `Builder` API provided a way to add this automatically, but we are bound to the interface [*laravel/scout*](https://github.com/laravel/scout) provides.

**Comment by zvermafia** [comment]
@kronthto wow it works, you're awesome man. Thank you!
Could you explain what is `title^3`?

**Comment by kronthto** [comment]
That's a boost. ES calculates a score how well the item matches and uses that for sorting. So in this example, a match in the title yields 3x the score-points and title-matches will be sorted above content-only matches.

**Comment by gabeta** [comment]
@kronthto It work very well for me thank thank

**Comment by NicksonYap** [comment]
@kronthto works like magic! Thanks!

**Comment by ctf0** [comment]
incase u want to add highlight, based on @kronthto & https://github.com/elastic/elasticsearch-php/issues/281#issuecomment-257172713
```php
$builder = MyModel::search(
    'searchstring',
    function (\Elasticsearch\Client $client, $query, $params) {
        $params['body'] = [
            'highlight' => [
                'fields' => [
                    '*' => new \stdClass(),
                ],
            ],

            'query' => [
                'multi_match' => [
                    'query' => $query,
                    'fuzziness' => 'AUTO',
                    'fields' => ['title^3', 'content'],
                ],
            ]
        ];

        return $client->search($params);
    }
);
```

**Comment by ctf0** [comment]
to get the highlight and any other data along with the model "if anyone have a better solution plz add it"

```php
$data = Model::search('searchstring', function (\Elasticsearch\Client $client, $query, $params) {
    // ...
})->raw();

return collect($data)->pluck('hits')->filter()->values()->flatten(1)->map(function ($v, $k) {
    return array_merge($v['_source'], [
        'highlight'=> $v['highlight'] ?? null,
        'score'    => $v['_score'],
    ]);
});
```

**Comment by reinierkors** [comment]
@kronthto When using this method my pagination stops working, any idea how to solve that?

**Comment by kronthto** [comment]
@reinierkors Are you using my version or the one *ctf0* posted (with highlighting)? [The latter one](https://github.com/ErickTamayo/laravel-scout-elastic/issues/59#issuecomment-397874642) completely overrides the `body` array, in which the keys `from`&`size` for the pagination [are set](https://github.com/ErickTamayo/laravel-scout-elastic/blob/fb5b843c0091972153cf36e009d53a631b2ec9da/src/ElasticsearchEngine.php#L151-L157).

You need to preserve those for pagination. Should work with a minor refactoring to: 
```php
$params['body']['highlight'] = [
    'fields' => [
        '*' => new \stdClass(),
    ],
];
$params['body']['query'] = [
    'multi_match' => [
        'query' => $query,
        'fuzziness' => 'AUTO',
        'fields' => ['title^3', 'content'],
    ],
];
```

**Comment by reinierkors** [comment]
Ah, thanks. Without overriding the body array it works, cheers.
