### ISSUE TITLE
AWS Elastic support?

### ISSUE THREAD

**Issue by Pashtunzoy** [ErickTamayo/laravel-scout-elastic#64]
I have looked everywhere for a simple and easy Laravel Scout Elasticsearch library and yours seems to be one of the best but you don't support Aws Elasticsearch with Signature Version 4 Authentication. 
I forked your repo and added Aws support and used in my project using the forked repo with composer.
So I just wanted to know if you are willing to adding the support and if so I can send you a pull request?
Will wait for your reply. 
Thanks

**Comment by ErickTamayo** [comment]
Not sure if this still valid, closing due to age.
