### ISSUE TITLE
Test with searchable models fails

### ISSUE THREAD

**Issue by standaniels** [ErickTamayo/laravel-scout-elastic#67]
It seems that in my tests indexing the created items isn't completed when I start searching for them. Does indexing happen asynchronously? How can I change this? My queue is already set to sync and `SCOUT_QUEUE` is set to `false`.

Here is an example of a test that keeps failing (Failed asserting that search results contain the given post).

Or isn't this an issue at all and would asserting the model's `toSearchableArray` suffice?

Any help is greatly appreciated.

```php
<?php

namespace Tests\Unit;

use App\Models\Category;
use App\Models\Post;
use App\Models\User;
use Tests\TestCase;

class SearchTest extends TestCase
{
    /** @test * */
    public function it_searches_the_whole_category_tree_for_posts()
    {
        // Given
        /** @var Category $parentCategory */
        $parentCategory = \factory(Category::class)->create([
            'title' => 'myParentCategory',
        ]);
        /** @var Category $childCategory */
        $childCategory = \factory(Category::class)->create();
        $childCategory->makeChildOf($parentCategory);
        /** @var Post $post */
        $post = \factory(Post::class)->create([
            'user_id' => \factory(User::class)->create()->id,
        ]);
        $post->requestCategories()->attach($childCategory);

        // When
        $searchResults = Post::search('myParentCategory')->get();

        // Then
        $this->assertTrue($searchResults->contains($post), 'Failed asserting that search results contain the given post.');
    }
}
```

**Comment by nikhiltri** [comment]
I'm looking at elasticsearch-php's info on mocking Elasticsearch for unit testing, but I'm not sure where to plug this logic in: https://github.com/elastic/elasticsearch-php#unit-testing-using-mock-a-elastic-client

**Comment by nikhiltri** [comment]
I have my setup working with a mocked Elasticsearch index: https://github.com/art-institute-of-chicago/data-aggregator/commit/6ee406089f81c7ee670a97b8e20648028abfb402

**Comment by zanematthew** [comment]
Pardon my ignorance, why are you using `cviebrock/laravel-elasticsearch` at https://github.com/art-institute-of-chicago/data-aggregator/blob/develop/composer.json#L9?

**Comment by zanematthew** [comment]
Are you sure this is using the mock results in the JSON file? I tried this approach, I'm unable to get this working with a mock JSON file.

Additionally; what is the reason for including your own elasticsearch in the app's composer.json, when this package already includes it?

And why create this `boot` method, https://github.com/art-institute-of-chicago/data-aggregator/commit/6ee406089f81c7ee670a97b8e20648028abfb402, when the package also already provides it; https://github.com/ErickTamayo/laravel-scout-elastic/blob/master/src/ElasticsearchProvider.php granted one is using the `ElasticBuilder`, and the other `Elasticsearch`. 

All that should be needed is to set the config within the unit test(?) `config(['elasticsearch.defaultConnection' => 'testing']);`.

Granted I'm unable to get your above approach to work. Unit test is in, but my test do not read results from the `'body' => fopen(base_path('tests/Unit/mockelasticsear...` path.

I think my issue lies within `'httpHandler'  => new GuzzleHttp\Ring\Client\MockHandler([`, I'll have to re-visit this tomorrow.

**Comment by zanematthew** [comment]
@nikhiltri 

I looked into the other package (https://github.com/cviebrock/laravel-elasticsearch) and it makes sense now.

The last issue I'm having is that during a unit test results are not being read from the json file. Elasticsearch is logging;

```
[2017-11-10 08:25:20] log.INFO: Request Success: {"method":"GET","uri":null,"headers":{"Host":["localhost:9200"],"Content-Type":["application/json"],"Accept":["application/json"]},"HTTP code":200,"duration":100} []
```

The file does exists, as if its not there the test will error out.

- Any suggestions?
- Also, why are you running `\Artisan::call('migrate');`, vs. the `use RefreshDatabase;` trait? Does the migrate command trigger something behind the scenes with ES?

I'm 90% sure my issue is a config issue, as the laravel log also shows;

```
[2017-11-10 08:50:27] testing.ERROR: Illegal string offset 'hits' {"userId":1,"email":"bobby.west@example.org","exception":"[object] (ErrorException(code: 0): Illegal string offset 'hits' at /home/vagrant/Code/my-app/vendor/tamayo/laravel-scout-elastic/src/ElasticsearchEngine.php:213)
```

So it seems that when the ES connection is made the HTTP request is not being caught by Guzzle(?)

**Comment by zanematthew** [comment]
I finally had a chance to dive back into my code. Ultimately I figured it would be redundant to test third party code, i.e., test the results of `App\Model::search('foo')`, figured at most just test code that you write. 

I ended up writing two silly test.


```php
<?php

namespace Tests\Unit;

use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class ScoutInstallTest extends TestCase
{
    use RefreshDatabase;

    /**
     * Verify the class uses Laravel Scout
     *
     * @group scout-install
     * @test
     */
    public function foo_model_uses_scout()
    {
        $this->assertTrue(in_array('Laravel\Scout\Searchable', class_uses('App\FooModel')));
    }

    /**
     * Verify that a searchable array does exists, and contains
     * the values we desire to search on.
     *
     * @group scout-install
     * @test
     */
    public function foo_model_has_valid_searchable_array()
    {
        $fooModel = factory(\App\FooModel::class)->create();

        $this->assertTrue([
            'title', // an array of keys that are being indexed.
        ] === array_keys($fooModel->toSearchableArray()));
    }
}
```

Note disable Laravel Scout in your testing environment; `<env name="SCOUT_DRIVER" value="null"/>`

**Comment by zanematthew** [comment]
@ErickTamayo This issue should be closed. There's enough info here, and other places for testing.

**Comment by standaniels** [comment]
Closing stale issue.
