### ISSUE TITLE
Question about asterisk surrounding query string

### ISSUE THREAD

**Issue by danvim** [ErickTamayo/laravel-scout-elastic#69]
I'm still learning Laravel and Elasticsearch.

When I tried searching using `GET` commands directly to my Elasticsearch server and compared to using Laravel Scout with your engine, I found that the results are different in the ordering of the results.

Upon further inspection, I found myself able to replicate the results by surrounding my query with asterisks by reading the code.

**May I ask, why were the asterisks there surrounding the query?**

Also, when I surrounded the query with asterisks, all the `_score`s became `1`? Isn't that useless in ordering the results?

https://github.com/ErickTamayo/laravel-scout-elastic/blob/master/src/ElasticsearchEngine.php#L134

**Comment by yukhnevych** [comment]
@danvim as far as I know asterisks used to replace zero or more characters, but in that case, it breaks search relevancy.

I have the same issue when I'm searching without asterisks, it works perfect, but when I add asterisks the search relevancy is broken.

Here is an article from elasticsearch docs about wildcards. https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-query-string-query.html#_wildcards

By the way, maybe you have found the solution?

**Comment by yukhnevych** [comment]
Also here is my fork from that repo, I've removed the asterisks
https://github.com/SergeyYukhnevich/laravel-scout-elastic

**Comment by danvim** [comment]
@SergeyYukhnevich Thanks. I haven't found a solution yet. But I'm tempted to get another Engine or spend some time learning and make my own. This library is too limited. As far as see, there is no way of changing the query object, which is too limiting.

The reason I wanted more control is I want to include Levenshtein distance fuzzy search.

Though I have to say, I just started learning Laravel and even more recent, Elasticsearch. I still have so much to learn. And still haven't found a good place/way to learn Elasticsearch. Official documentation seems to be too scattered and confusing.
