### ISSUE TITLE
Where Clauses

### ISSUE THREAD

**Issue by ahmadarif** [ErickTamayo/laravel-scout-elastic#74]
I get an error when using this code
`Post::search($keyword)->where('id', '>', 6)->get();`

What's the code for needs like this?

**Comment by kronthto** [comment]
The [definition of the `where` method](https://github.com/laravel/scout/blob/v3.0.7/src/Builder.php#L98) allows only 2 Parameters. That is an limitation of laravel/scout itself, not this Elastic driver. It is also mentioned in the docs: https://laravel.com/docs/master/scout#where-clauses

**Comment by ahmadarif** [comment]
Oh i see, thanks for information.
So, I just can manipulate after ES process the search function?

**Comment by kronthto** [comment]
In a project in my company we also need more complex searches, so we use a custom fork of this driver that has #56 merged. This way we can pass what we like to Elastic.

**Comment by ahmadarif** [comment]
Very nice, I will try this solution.
Thank's very much @kronthto :D

**Comment by ErickTamayo** [comment]
#56 has been merged.
