### ISSUE TITLE
Laravel 5.5

### ISSUE THREAD

**Issue by mrmonat** [ErickTamayo/laravel-scout-elastic#76]
When will Laravel 5.5 will be supported?

**Comment by ErickTamayo** [comment]
I'm gonna work on this tomorrow

**Comment by ErickTamayo** [comment]
hey @mrmonat I noticed that there were no changes in scout regarding version bump so this package should be already compatible with 5.5.

**Comment by xcaptain** [comment]
I tested with laravel 5.5, it works well!

**Comment by mrmonat** [comment]
Okay, you are right, it works. But package autodiscover would be nice to have :)
