### ISSUE TITLE
Search Error: Fielddata is disabled on text fields by default. 

### ISSUE THREAD

**Issue by jackie-d** [ErickTamayo/laravel-scout-elastic#77]
Hi, 
 Laravel 5.4, ES 5.2.0.

Importing fine, but on search I get: 

`(1/1) BadRequest400Exception
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [name] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"xxxxxxxxx","node":"GMpAuk7dRzSA0TVfY5EwNA","reason":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [name] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory."}}],"caused_by":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [name] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory."}},"status":400}`

Any hint?

Thanks.

**Comment by alexTitakoff** [comment]
++

**Comment by mvehar-preskok** [comment]
Any response on this one?
