### ISSUE TITLE
use elasticsearch to store relation data

### ISSUE THREAD

**Issue by xcaptain** [ErickTamayo/laravel-scout-elastic#78]
Currently scout support saving custom fields into ES using `toSearchableArray`, but when getting data from    ES, the returned keys are the same with model keys.

So how about return the whole document in ES so we don't need to do manual sql join to get additional data.

**Comment by rasim** [comment]
$array = $this->toArray(); // model columns

        $extra_data = [];
        $extra_data['category_name'] = $this->category->NAME; // add relationship column

        $merge_array = array_merge($array, $extra_data); // merge model columns and add relationship columns
        
        return array_only($merge_array, [
            'category_name'
        ]); // set index columns

**Comment by kronthto** [comment]
This puts the relation data into ES and you can get search-hits for the category name in your example, but I think @xcaptain s intention is to prevent costly queries after the ES search is done and the Model entities are being contructed.

Right now, not just the relations, even the "Base-Model"s are fetched by ID from the DB again after search: https://github.com/ErickTamayo/laravel-scout-elastic/blob/85bc852ca059910c77d98c6960e7999a6cec5ea6/src/ElasticsearchEngine.php#L210-L215

Definitely an interesting idea, I also maintain a project where there are thousands of Keywords associated with Assets indexed in ES, and right now, all of these are queried from the DB even though I have them in ES.

**Comment by xcaptain** [comment]
@kronthto That's exactly what I mean,  these piece of code limited the returned keys, it can be extended to return more keys. I'm going to make a PR on this.

**Comment by xcaptain** [comment]
@kronthto   @ErickTamayo   Can you review this change. https://github.com/ErickTamayo/laravel-scout-elastic/pull/79
