### ISSUE TITLE
count method warning in php7.2

### ISSUE THREAD

**Issue by xcaptain** [ErickTamayo/laravel-scout-elastic#80]
https://github.com/ErickTamayo/laravel-scout-elastic/blob/85bc852ca059910c77d98c6960e7999a6cec5ea6/src/ElasticsearchEngine.php#L206

since php7.2, count a number will generate a warning, also count a number seems to be meaningless, I suggest change it to be `if ($results['hits']['total'] === 0)`

**Comment by ErickTamayo** [comment]
A PR is very welcome!
