### ISSUE TITLE
Return all results (not default max of 10)

### ISSUE THREAD

**Issue by kJamesy** [ErickTamayo/laravel-scout-elastic#82]
I have used this package in production and only just noticed that Elastic Search gives me a [maximum of 10 results](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html) by default.

So if I do 
`Model::search('text')->get();`
I get only 10 results.

Whereas if I do:
`Model::search('text')->paginate( (int) $aBigNumber );`
I get a maximum of `(int) $aBigNumber` results.

Is there a way to get **all** results when I use `get()`?

**Comment by kronthto** [comment]
You cannot get **all** results, as the maximum that Elastic is capable of returning is 10.000.

You can achieve that using `get()` though by setting the `limit` property: 
```php
$query = Model::search('text');
$query->limit = 10000;
$query->get();
```

**Comment by kJamesy** [comment]
Makes sense. Many thanks

**Comment by artsur** [comment]
`Model::search('text')->take(20)->raw()`
 or 
`Model::search('text')->take(20)->get()`
