### ISSUE TITLE
Debug query to see why response is empty

### ISSUE THREAD

**Issue by rockymontana** [ErickTamayo/laravel-scout-elastic#88]
Hey!
Thanks for this package!
I wonder if it’d be possible to make a debug feature to return the actual query that is being sent to ElasticSearch?

I’ve successfully imported all my model data, but when I search I get an empty response.
To be able to determine why that is I would need to see the request being sent into ES.
When I query ES from kibana I can see that the DB is populated though.

Thanks a big bunch!
Jonas

**Comment by kronthto** [comment]
This library uses [`elasticsearch/elasticsearch`](https://github.com/elastic/elasticsearch-php) under the hood, so if it's just for debugging purposes I would suggest to simply edit in an output close before the request is sent, like here: https://github.com/elastic/elasticsearch-php/blob/c0ed43cff390820a0621004df9e5785ff9c12e65/src/Elasticsearch/Client.php#L1571 - in your `vendor/elasticsearch/elasticsearch` directory, and revert afterwards.
