### ISSUE TITLE
Laravel 5.3 Unresolvable dependency

### ISSUE THREAD

**Issue by fridzema** [ErickTamayo/laravel-scout-elastic#9]
Dear Erick,

I tried to use your package to an almost clean laravel 5.3 installation on php7.

When i place your `ScoutEngines\Elasticsearch\ElasticsearchProvider::class` in the providers array i get the following error:
`[Illuminate\Contracts\Container\BindingResolutionException]                                               
  Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\Manager`

Do you have any idea what is wrong?

Have a great evening!

**Comment by ErickTamayo** [comment]
Hello! 

Certainly that is odd, is that the only stack trace that it gives to you? Can you check in your logs for more info and paste it here?

And also can you run `composer dump` and check if that fixes your error?

**Comment by fridzema** [comment]
Sorry, my bad!
I had forgotten to add the `Laravel\Scout\ScoutServiceProvider::class` to my providers array :(

**Comment by ErickTamayo** [comment]
:) NP!
