### ISSUE TITLE
toSearchableArray() is not working.

### ISSUE THREAD

**Issue by robbietorinit** [ErickTamayo/laravel-scout-elastic#97]
Hi,
I have customised the array to be indexed. But although it doesn't work. I have tried deleting the old index first then tried to import all at once using 

php artisan scout:import "App\Product"

public function toSearchableArray()
{
        $array = $this->toArray();
        $newArray = [];
        $newArray['product_name'] = $array['product_name'];
        $newArray['product_description'] = $array['product_description'];
        $newArray['price'] = $array['price'];
        $newArray['category'] = $array['category'];
        return $newArray;
 }

Can anyone please tell me what seems to be the problem?

**Comment by Smulllyn112** [comment]
The same problem here. I dont understand
